/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programaunidad2fundamentostelecom;

import java.util.Vector;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;
import java.awt.Color;

/**
 *
 * @author Jasive
 */
public class sumaDeComp extends javax.swing.JFrame {

	/**
	 * Creates new form sumaDeComp
	 */
	public sumaDeComp() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		txtOracion = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableOrigen = new javax.swing.JTable();
		txtOrigen = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		txtPrueba = new javax.swing.JTextArea();
		resultadoOrigen = new javax.swing.JLabel();
		resultadoOrigen.setBackground(Color.WHITE);
		resultadoOrigen.setOpaque(true);
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		txtOracion.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				txtOracionKeyReleased(evt);
			}
		});

		String[] title = new String[] { "Letra", "Binario" };
		Object[][] data = {};
		tModel = new DefaultTableModel(data, title);

		jTableOrigen.setModel(tModel);

		jTableOrigen.getColumnModel().getColumn(0).setPreferredWidth(49);
		jTableOrigen.getColumnModel().getColumn(1).setPreferredWidth(115);
		jScrollPane1.setViewportView(jTableOrigen);

		txtOrigen.setText("txtOrigen");
		txtOrigen.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtOrigenActionPerformed(evt);
			}
		});

		txtPrueba.setColumns(20);
		txtPrueba.setRows(5);
		txtPrueba.setWrapStyleWord(true);
		jScrollPane2.setViewportView(txtPrueba);
		


		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(58)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(txtOracion, GroupLayout.PREFERRED_SIZE, 455, GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(resultadoOrigen, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
								.addGroup(Alignment.LEADING, layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 220, GroupLayout.PREFERRED_SIZE)))
							.addGap(18)
							.addComponent(txtOrigen, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)
							.addGap(45)
							.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(192, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(19)
					.addComponent(txtOracion, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
							.addComponent(txtOrigen, GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
							.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(resultadoOrigen, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
					.addGap(43))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void txtOracionKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtOracionKeyReleased
		String cadena = txtOracion.getText();
		resultadoOrigen.setText("");
		Vector<Object> fila;
		
		//Limpia la tabla 
        for(int i = tModel.getRowCount(); i>0; i--)
        	tModel.removeRow(i-1);
        	
        int resultado =0;
		for (int a = 0; a < cadena.length(); a++) {
			// conversión a binario de cada uno de los caracteres
			
			resultado+= (int) cadena.charAt(a);
			String temporal = Integer.toBinaryString(cadena.charAt(a));
			fila    = new Vector<Object>();
        	fila.add(cadena.charAt(a));
            fila.add(temporal);
            tModel.addRow(fila);
		}
		String temp = Integer.toBinaryString(resultado);
		resultadoOrigen.setText(temp);
		
	}// GEN-LAST:event_txtOracionKeyReleased

	private void txtOrigenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtOrigenActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtOrigenActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(sumaDeComp.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(sumaDeComp.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(sumaDeComp.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(sumaDeComp.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new sumaDeComp().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTableOrigen;
	private javax.swing.JLabel resultadoOrigen;
	private javax.swing.JTextField txtOracion;
	private javax.swing.JTextField txtOrigen;
	private javax.swing.JTextArea txtPrueba;
	private javax.swing.table.DefaultTableModel tModel;
}
